USE ASSIGN_DB;

--1
SELECT * FROM ORDERS AS O
INNER JOIN USERS AS U ON O.USER_ID = U.USER_ID
INNER JOIN BOOKS AS B ON O.PRODUCT_ID = B.PRODUCT_ID;

--2
SELECT USER_ID,COUNT(*) TOTAL_ORDERS FROM ORDERS GROUP BY USER_ID

--3
SELECT U.NAME,B.TITLE FROM ORDERS AS O
INNER JOIN USERS AS U ON U.USER_ID = O.USER_ID
INNER JOIN BOOKS AS B ON O.PRODUCT_ID = B.PRODUCT_ID WHERE B.TITLE = 'HALF-GIRLFRIEND'

--4
SELECT U.NAME,B.TITLE FROM ORDERS AS O
INNER JOIN USERS AS U ON U.USER_ID = O.USER_ID
INNER JOIN BOOKS AS B ON O.PRODUCT_ID = B.PRODUCT_ID WHERE B.PRODUCT_ID IN (102,103,104,105,106) ORDER BY B.PRODUCT_ID ASC

--5
SELECT U.NAME,SUM(B.PRICE) TOTAL_AMOUNT FROM ORDERS AS O
INNER JOIN USERS AS U ON U.USER_ID = O.USER_ID
INNER JOIN BOOKS AS B ON O.PRODUCT_ID = B.PRODUCT_ID GROUP BY U.NAME;

--6
SELECT TOP 1 U.NAME,SUM(B.PRICE) TOTAL_AMOUNT FROM ORDERS AS O
INNER JOIN USERS AS U ON U.USER_ID = O.USER_ID
INNER JOIN BOOKS AS B ON O.PRODUCT_ID = B.PRODUCT_ID GROUP BY U.NAME ORDER BY TOTAL_AMOUNT DESC 

--7 
SELECT TITLE,PRICE FROM BOOKS ORDER BY PRICE DESC

--8
SELECT TOP 1 TITLE,PRICE FROM BOOKS ORDER BY PRICE DESC

--9 
SELECT TOP 1 TITLE,PRICE FROM BOOKS ORDER BY PRICE ASC

--10
SELECT TOP 1 TITLE,PRODUCT_ID FROM BOOKS ORDER BY PRODUCT_ID DESC


