USE ASSIGN_DB;

--LIST OF UNIQUE STUDENT NAMES
SELECT * FROM STUDENTS2024 UNION SELECT * FROM STUDENTS2025;

--LIST OF ALL STUDENT NAMES INCLUDING DUPLICATES
SELECT* FROM STUDENTS2024 UNION ALL SELECT * FROM STUDENTS2025;

--EMPLOYEE NAMES IN UPPERCASE
SELECT  EMP_ID,UPPER(EMP_NAME) EMP_NAME FROM  EMPLOYEES;

--LENGTH OF EACH EMPLOYEE NAME
SELECT  EMP_ID,EMP_NAME,LEN(EMP_NAME) EMP_NAME_LENGHT FROM  EMPLOYEES;

--FIRST 3 LETTERS OF EMPLOYEE NAMES
SELECT EMP_ID,EMP_NAME, SUBSTRING(EMP_NAME,1,3)EMP_NAME_F3 FROM EMPLOYEES

--REPLACE FINANCE DEPT WITH ACCOUNTS
SELECT * FROM EMPLOYEES;
SELECT EmpID,Name, REPLACE(Department,'Finance','Accounts') Department FROM EMPLOYEES;

--NEW COL "NAME-DEPT" 
SELECT *,CONCAT(Name,Department) 'Name-Department' FROM EMPLOYEES;

--TODAY'S DATE
SELECT GETDATE() DATE_TIME_TODAY;

--DIFFERENCE BETWEEN PROJECTS
SELECT * FROM PROJECTS;
SELECT Name,DATEDIFF(DAY,StartDate,EndDate) AS PROJECT_DURATION FROM PROJECTS;

--ADDING 10 DAYS TO PROJECT DATES
SELECT Name,StartDate,EndDate,DATEADD(DAY,10,EndDate) AS UPDATED_PROJECT_END_DATE FROM PROJECTS;

--DAYS LEFT FROM PROJECT TO END
SELECT Name,DATEDIFF(DAY,CONVERT(DATE,GETDATE(),101),EndDATE) AS DAYS_LEFT FROM PROJECTS;

--CAST DATE TIME 
SELECT CONVERT(VARCHAR(10),GETDATE(),103) AS DATE_DDMMYYYY; 

--CONVERTING FLOAT TO CAST
SELECT CAST(123.456 AS INT);